[workspace]
members = ["cutout", "predicate_improv"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[package]
name = "paideia_storytelling"
version.workspace = true
edition.workspace = true
